### PR TITLE
strings.xml: Fixes

### PR DESCRIPTION
**Pull request by laststandrighthere**

### CODE REVIEW

**Comment by laststandrighthere** [comment]
oof sultan mode on
added some fixes too

**Comment by franciscofranco** [comment]
I hven't updated strings.xml so you "wasted" sometime on an older file. Most strings should be the same so you won't have to make too many conflict changes I believe. Will upload newer strings asap.

**Comment by franciscofranco** [comment]
https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/commit/2a3fb1adcf78f12027799a2acae0f64b3847286f

**Comment by laststandrighthere** [comment]
Fixed conflicts

**Comment by franciscofranco** [comment]
Included some of those fixes in the next version, thanks.

**Pull request closed without merging**
